const product = [
  {
    product_name: "Paneer Butter Masala",
    sku: "paneer-butter-masala",
    description: "Soft paneer cubes cooked in rich tomato butter gravy",
    category: ["Main Course", "South Indian"],
    price: 250.0,
    discount: 20.0,
    final_price: 230.0,
    is_veg: true,
    is_available: true,
    preparation_time: 20,
    rating: 4.5,
    image_url: "https://example.com/images/paneer_butter_masala.jpg",
  },

  {
    product_id: "02",
    product_name: "Briyani",
    description: "Tender and juicly chicken with aromatic rice",
    category: ["Main Course", "South Indian"],
    price: 250.0,
    discount: 20.0,
    final_price: 230.0,
    is_veg: false,
    is_available: true,
    preparation_time: 20,
    rating: 4.5,
    image_url: "https://example.com/images/paneer_butter_masala.jpg",
    created_at: "2024-10-12T10:30:00Z",
    updated_at: "2024-12-01T15:45:00Z",
  },

  {
    product_id: "03",
    product_name: "Naan",
    description: "Not Maida pure wheat butter roti",
    category: ["Main Course", "North Indian"],
    price: 250.0,
    discount: 20.0,
    final_price: 230.0,
    is_veg: true,
    is_available: true,
    preparation_time: 20,
    rating: 4.5,
    image_url: "https://example.com/images/paneer_butter_masala.jpg",
    created_at: "2024-10-12T10:30:00Z",
    updated_at: "2024-12-01T15:45:00Z",
  },

  {
    product_id: "04",
    product_name: "Idly",
    description: "soft and smoochy",
    category: ["Main Course", "South Indian"],
    price: 250.0,
    discount: 20.0,
    final_price: 230.0,
    is_veg: true,
    is_available: true,
    preparation_time: 20,
    rating: 4.5,
    image_url: "https://example.com/images/paneer_butter_masala.jpg",
    created_at: "2024-10-12T10:30:00Z",
    updated_at: "2024-12-01T15:45:00Z",
  },

  {
    product_id: "05",
    product_name: "Dosa",
    description: "Crisp and roasted corner",
    category: ["Main Course", "South Indian"],
    price: 250.0,
    discount: 20.0,
    final_price: 230.0,
    is_veg: true,
    is_available: true,
    preparation_time: 20,
    rating: 4.5,
    image_url: "https://example.com/images/paneer_butter_masala.jpg",
    created_at: "2024-10-12T10:30:00Z",
    updated_at: "2024-12-01T15:45:00Z",
  },
];
